language: julia
julia:
  - nightly
  - 1.0
os:
  - linux
branches:
  only:
    - master
notifications:
  email: false
git:
  depth: 99999999
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
after_success:
  - julia -e 'using Pkg;
              import Glob;
              cd(dirname(dirname(pathof(Glob))));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(Coveralls.process_folder())'
