name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
jobs:
  test:
    name: Julia ${{ join(matrix.*, ' - ') }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0'
          - '1.6'
          - '1.8'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x86
          - version: '1'
            os: windows-latest
            arch: x64
          - version: '1'
            os: macos-latest
            arch: x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
          flag-name: Julia ${{ join(matrix.*, ' - ') }}
          parallel: true
  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
